### ISSUE TITLE
BUG: #linkers not adding linkers to designs

### ISSUE THREAD

**Issue by kcurran1** [demetrixbio/GslCore#22]
This bug may be related to #21. I created a GSL document to test whether adding linkers to the design would change the behavior of the duplications and primer validation issues. Instead, what I am finding is that I cannot get the linkers into the design at all.  

Here is the GSL and command I was using to test:

```
#refgenome S288C

//stitch with linkers
#platform stitch
#linkers 0,2,3,9 | 
pURA3; gTDH3; tCYC1

//megastitch with linkers
#platform megastitch
#linkers 0,2,3,4,9 | 0,2,3,4,9
pURA3; gTDH3; tCYC1; ###; !tCYC1; !gTDH3; !tCYC1
```

`bin/Gslc/net7.0/Gslc.exe --snapgene . test designs/test1.gsl --seamless false --noprimers`

I had to add the `--noprimers` due to the primer validation issue, but I believe the linkers should be added regardless.

@daz10000

**Comment by daz10000** [comment]
Fixed in 0.5.1 just released.
